apiVersion: v1
data:
  config.yml: "servers:\n\n   - host: \"rabbitmq\"\n     port: 15672\n     useSSL:
    false\n     username: \"guest\"\n     password: \"guest\"\n     encryptedPassword:
    \"\"\n     displayName : \"Server2\"\n\nconnection:\n  socketTimeout: 10000\n
    \ connectTimeout: 10000\n\n############\n## Queue Group Configuration. The queue
    stats will be grouped by the 'groupName'\n## if the 'queueNameRegex' matches the
    name of the Queue.\n\n## groupName            The stats from Queues matched by
    the 'queueNameRegex' will be reported under this name\n## queueNameRegex       A
    Regex to match the Queue Name\n## showIndividualStats  If set to false then the
    Individual Queue stats will not be reported.\n##                      This will
    help if there are several short lived queues and an explosion of metrics\n##                      in
    the controller can be avoided\n############\n\n# Uncomment the following lines
    for configuration\nqueueGroups:\n- groupName: group1\n  queueNameRegex: queue.+\n
    \ showIndividualStats: false\n\n# Queue Group Configuration\n#- groupName: group2\n#
    \ queueNameRegex: temp.+\n#  showIndividualStats: false\n\nfilter:\n  nodes:\n
    \   includes: [\".*\"]\n  queues:\n    includes: [\".*\"]\n\nendpointFlags:\n
    \ federationPlugin: \"false\"\n  overview: \"true\"\n\nencryptionKey: \"myKey\"\n\n#
    number of concurrent tasks\nnumberOfThreads: 15\n\n\n#This will create this metric
    in all the tiers, under this path\n#metricPrefix: Custom Metrics|RabbitMQ|\n\n#This
    will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID>
    with the appropriate one from your environment.\n#To find the <COMPONENT_ID> in
    your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java\nmetricPrefix:
    Server|Component:<TIER ID>|Custom Metrics|RabbitMQ|\n\n# Default information needs
    to be updated\ncontrollerInfo:\n  controllerHost: \"controller\"\n  controllerPort:
    8080\n  account: \"customer1\"\n  username: \"user1\"\n  password: \"welcome\"\n
    \ encryptedPassword: \"\"\n  encryptionKey: \"\"\n  controllerSslEnabled: false\n
    \ enableOrchestration: false\n  uniqueHostId: \"\"\n  accountAccessKey: \"\"\n
    \ machinePath: \"\"\n  simEnabled: true\n  applicationName: \"\"\n  tierName:
    \"\"\n  nodeName: \"\"\n\nenableHealthChecks: false\n  "
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: extension-config
