AWSTemplateFormatVersion: 2010-09-09
Description: Root CloudFormation template for creating nested stack.
# Parameters:
  # TemplateS3Bucket:
  #   Description: The bucket url for templates
  #   Type: String
  #   Default: https://cf-templates-dyf6dzirmcya-eu-west-2.s3.eu-west-2.amazonaws.com
Resources:
  SecretsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-dyf6dzirmcya-eu-west-2.s3.eu-west-2.amazonaws.com/2021015p2N-CF_Secret_ECSFargate.yaml
  TaskDefinitionStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
     - SecretsStack
    Properties:
      TemplateURL: https://cf-templates-dyf6dzirmcya-eu-west-2.s3.eu-west-2.amazonaws.com/2021015GFE-CF_Cluster_ECSFargate.yaml
      Parameters:
        AppDSecretAccessKey: 
          Fn::GetAtt: 
          - SecretsStack
          - Outputs.AppdSecretArn
  ClusterStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
     - TaskDefinitionStack
    Properties:
      TemplateURL: arn:aws:cloudformation:eu-west-2:032263611943:stack/cluster-st/4b6a2e40-5742-11eb-8b93-020bd115d06c
      Parameters:
        TaskDefinition:
          Fn::GetAtt: 
          - TaskDefinitionStack
          - Outputs.TaskDefinitionArn
  