apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  selector:
    name: nodejs-app
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appd-nodejs-deployment-auto
  labels:
    appName: NodeJS-Deployment-Auto-App
    name: appd-nodejs-deployment-auto
spec:
  selector:
    matchLabels:
      name: nodejs-app
  replicas: 1
  template:
    metadata:
      labels:
        app: appd-nodejs-deployment-auto
        tier: backend
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: nodejs-app
          image: sashaz/openmct:v1
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 200m
              memory: 500M
            requests:
              cpu: 100m
              memory: 300M
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: appd-nodejs-config
          env:
          - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: appd-secrets
                key: account-access-key
      restartPolicy: Always