apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-pod-init
spec:
  selector:
    name: dotnet-app-pod-init
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: dotnet-app-pod-init
  name: dotnet-app-pod-init
spec:
  initContainers:
  - image: appdynamics/dotnet-core-agent:20.7.0 # agent image
    name: appd-agent
    command:
      - cp
      - -ra
      - /opt/appdynamics/.
      - /opt/appd
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /opt/appd
      name: appd-agent-volume
  containers:
  - image: microsoft/dotnet-samples:aspnetapp # application image
    name: dotnet-app-pod-init
    resources: 
      limits:
        cpu: 200m
        memory: 500M
      requests:
        cpu: 100m
        memory: 300M
    envFrom:
    - configMapRef:
        name: appd-dotnet-config
    env:
    - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: appd-secrets
          key: account-access-key
    - name: APPDYNAMICS_AGENT_APPLICATION_NAME
      value: OpenShift-DotNet-Application
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /opt/appd/dotnet
      name: appd-agent-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: appd-agent-volume
    emptyDir: {}
status: {}
