#=====
instrumentationConfig:
  enabled: true
  defaultEnv: JAVA_TOOL_OPTIONS
  instrumentationMethod: Env
  appNameStrategy: label # name by label!
  appNameLabel: appName
  nsToInstrumentRegex: appd-dotnet-agent|java-project|dev
  defaultAppName: sample-app
  #defaultCustomConfig: "-Dhello -Dhi -Daloha"
  numberOfTaskWorkers: 3
  imagePullPolicy: Always
  defaultInstrumentationLabelMatch:
    - language: java
    - language: dotnet
  instrumentationRules:
    - matchString: java # Regular expression to match on deployment name, defaultInstrumentMatchString provides default
      #namespaceRegex: apm
      #appNameLabel: appName
      #customAgentConfig: "-Dhola"
      appName: Sample-Java-Rule
      tierName: TIER_ONE
      env: JAVA_OPTS
      instrumentContainer: all
      runAsUser: 100
      runAsGroup: 100
      language: java
      imageInfo:
        image: "docker.io/appdynamics/java-agent:latest"
        agentMountPath: "/opt/appdynamics"
        imagePullPolicy: "IfNotPresent"
    - labelMatch:
       - language: dotnet
      appNameLabel: appName
      instrumentContainer: all
      language: dotnetcore
      imageInfo:
        image: "docker.io/appdynamics/dotnet-core-agent:latest"
        agentMountPath: /opt/appdynamics
        imagePullPolicy: "IfNotPresent"
#=====

