apiVersion: v1
data:
  shim.js: "require(\"appdynamics\").profile({\n
    \ controllerHostName: process.env.APPDYNAMICS_CONTROLLER_HOST_NAME,\n  controllerPort:
    process.env.APPDYNAMICS_CONTROLLER_PORT, \n  controllerSslEnabled: process.env.APPDYNAMICS_CONTROLLER_SSL_ENABLED,
    \ // Set to true if controllerPort is SSL\n  accountName: process.env.APPDYNAMICS_AGENT_ACCOUNT_NAME,\n
    \ accountAccessKey: process.env.APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY, //required\n
    \ applicationName: process.env.APPDYNAMICS_AGENT_APPLICATION_NAME,\n  tierName:
    process.env.APPDYNAMICS_AGENT_TIER_NAME, \n  reuseNode: process.env.APPDYNAMICS_AGENT_REUSE_NODE_NAME,\n  reuseNodePrefix:
    process.env.APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX,\n });\n require(process.env.APP_ENTRY_POINT)"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: appd-shim