apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-pod-auto
spec:
  selector:
    name: dotnet-app-pod-auto
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: dotnet-app-pod-auto
  name: dotnet-app-pod-auto
spec:
  containers:
  - image: microsoft/dotnet-samples:aspnetapp # application image
    name: dotnet-app-pod-auto
    resources: 
      limits:
        cpu: 200m
        memory: 500M
      requests:
        cpu: 100m
        memory: 300M
    envFrom:
    - configMapRef:
        name: appd-dotnet-config
    env:
    - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: appd-secrets
          key: account-access-key
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
