apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-infra
spec:
  selector:
    name: dotnet-app-infra
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: dotnet-app-infra
  name: dotnet-app-infra
spec:
  initContainers:
  - image: appdynamics/dotnet-core-agent:20.7.0
    name: appd-agent-infra
    command:
      - cp
      - -ra
      - /opt/appdynamics/.
      - /opt/appd
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /opt/appd
      name: appd-agent-volume
  containers:
  - image: microsoft/dotnet-samples:aspnetapp
    name: dotnet-app-infra
    resources: 
      limits:
        cpu: 100m
        memory: 100M
        #ephemeral-storage: 100M # for emptyDir, feature-gate ResourceEphemeralStorage
      requests:
        cpu: 50m
        memory: 100M
        #ephemeral-storage: 100M
    #command: ["/bin/sh"]
    #args: ["&& /bin/sh -c UNIQUE_HOST_ID=$(sed -rn '1s#.*/##; 1s/docker-(.{12}).*/\\1/p' /proc/self/cgroup)"]
    #command: ["/scripts/wrapper.sh"]
    # APPDYNAMICS_AGENT_UNIQUE_HOST_ID=$(sed -rn '1s#.*/##; 1s/docker-(.{12}).*/\1/p' /proc/self/cgroup)
    # fieldPath: spec.nodeName is localhost
    command: ["/bin/sh"]
    args: ["-c", "UNIQUE_HOST_ID=$(sed -rn '1s#.*/##; 1s/docker-(.{12}).*/\\1/p' /proc/self/cgroup) && dotnet aspnetapp.dll"]
    envFrom:
    - configMapRef:
        name: appd-dotnet-config
    env:
    - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: appd-secrets
          key: account-access-key
    - name: APPDYNAMICS_AGENT_APPLICATION_NAME
      value: OpenShift-DotNet-Application-Infra
    - name: METADATA_UID
      valueFrom:
        fieldRef:
          fieldPath: metadata.uid
    - name: APPDYNAMICS_AGENT_UNIQUE_HOST_ID
      value: $(UNIQUE_HOST_ID)
    - name: APPDYNAMICS_AGENT_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    ports:
    - containerPort: 80
    volumeMounts:
    - name: appd-agent-volume
      mountPath: /opt/appd/dotnet
    #- name: env-vars-wrapper
    #  mountPath: /scripts
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: appd-agent-volume
    emptyDir: {}
  #- name: env-vars-wrapper
  #  configMap:
  #    name: wrapper
  #    defaultMode: 0744
status: {}
