apiVersion: v1
data:
  ACCOUNT_ACCESS_KEY: cdd4d5d3-ac1b-4101-a934-ad72fba37f31
  ACCOUNT_NAME: customer1
  APPLICATION_NAME: OpenShift-3.11
  CONTROLLER_HOST: nwmaas-2081nosshcontro-dw1rwn6a.appd-cx.com
  CONTROLLER_PORT: "8090"
  CONTROLLER_SSL_ENABLED: "false"
  EVENT_ENDPOINT: nwmaas-2081nosshcontro-dw1rwn6a.appd-cx.com:9080
  FULL_ACCOUNT_NAME: customer1_e6e12e4a-46cd-42e2-8cbe-beb7d395ef27
  RANDOM_ENV_VAR: value_here
kind: ConfigMap
metadata:
  name: appd-controller-config