apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: "Kubernetes-Operator-20.11.0" #"<app-name>"
  controllerUrl: "http://nwmaas-20100nosshcontr-r6y4tftd.appd-cx.com:8090" # "<protocol>://<appdynamics-controller-host>:<port>"
  account: "customer1" # "<account-name>"
  image: "docker.io/appdynamics/cluster-agent:20.11.0" # docker image info
  serviceAccountName: appdynamics-cluster-agent
  # all of the following parameters are optional
  nsToMonitor:
    - "default"
    - "dev"
    - "staging"
  # podFilter:
  #   blocklistedLabels:
  #     - label1: value1
  #   allowlistedLabels:
  #     - label1: value1
  #     - label2: value2
  #   allowlistedNames:
  #     - name1
  #   blocklistedNames:
  #     - name1
  #     - name2
  logLevel: "INFO"
  stdoutLogging: "true"
   # Auto-instrumentation config
  instrumentationMethod: Env
  appNameStrategy: label
  appNameLabel: name
  nsToInstrumentRegex: appd-dotnet-agent|dotnetcore-project|java-project
  instrumentationRules:
    - namespaceRegex: appd-dotnet-agent
      appNameLabel: appName
      language: dotnetcore
      imageInfo:
        image: "docker.io/appdynamics/dotnet-core-agent:latest"
        agentMountPath: /opt/appdynamics
    - namespaceRegex: java-project
      appNameLabel: appName
      language: java
      imageInfo:
        image: "docker.io/appdynamics/java-agent:latest"
        agentMountPath: "/opt/appdynamics"
        imagePullPolicy: "IfNotPresent"
