apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: dotnet-app
  name: dotnet-app-operator
spec:
  containers:
  - image: microsoft/dotnet-samples:aspnetapp
    name: dotnet-app
    resources: 
      limits:
        cpu: 200m
        memory: 500M
      requests:
        cpu: 100m
        memory: 300M
    envFrom:
    - configMapRef:
        name: appd-dotnet-config
    - configMapRef:
        name: appd-controller-config
    env:
    - name: APPDYNAMICS_AGENT_APPLICATION_NAME
      value: OpenShift-DotNet-Operator
    - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: appd-secrets
          key: account-access-key
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
