apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    name: flask-app
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appd-python-no-image-updates
  labels:
    name: appd-python--no-image-updates
spec:
  selector:
    matchLabels:
      name: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        name: flask-app
    spec:
      serviceAccountName: appd-account
      volumes:
      - name: agent-config
        configMap:
          name: agent-config-python
      containers:
        - name: webapp
          image: alexappd/python-flask-docker-no-instr:latest # image that contains application only, no instrumentation
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "pip install -U appdynamics==20.11.0.2783 && pyagent run -c /opt/appdynamics/agent.cfg python app/app.py"]
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 500m
              memory: 500M
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: agent-config
              mountPath: /opt/appdynamics/agent.cfg
              subPath: agent.cfg
          
