AWSTemplateFormatVersion: 2010-09-09
Description: An CloudFormation template for creating a secret. Creates AppDynamics account access key secret.
Parameters:
  AppdAccountSecretKey:
    Type: String
    Default: cdd4d5d3-ac1b-4101-a934-ad72fba37f31
Resources:
  #This is a Secret resource with a randomly generated password in its SecretString JSON.
  MySecretA:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: APPDYNAMICS_ACCOUNT_ACCESS_KEY
      Description: "AppDynamics controller's secret access key"
      SecretString: !Ref AppdAccountSecretKey