# app-vault-secret.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appd-app
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-agent-demo
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-appdaccesskey: "secret/appd/config"
        vault.hashicorp.com/agent-inject-template-appdaccesskey: |
          {{- with secret "secret/appd/config" -}}
            {{ .Data.data.appd_access_key }}
          {{- end }}
        vault.hashicorp.com/role: "appd-role"
    spec:
      serviceAccountName: appd-app
      containers:
      - name: app
        image: jweissig/app:0.0.1 #todo try to create secret in the namespace
        resources: 
          limits:
            cpu: "0.5"
            memory: 500M
          requests:
            cpu: "0.3"
            memory: 300M
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: JWT_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: SERVICE_PORT
          value: "8080"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appd-app
  labels:
    app: vault-agent-demo