apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: machine-agent-extension
  name: machine-agent-extension
spec:
  containers:
  - image: alexappd/apigee-extension:latest  #todo replace with extension image name
    name: machine-agent-extension
    resources: 
      limits:
        cpu: 100m
        memory: 100M
      requests:
        cpu: 50m
        memory: 100M
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
